name: Bug Report(draft)
description: File a bug/issue
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    id: wordpress-version
    attributes:
      label: WordPress version
      placeholder: ex. 6.7.1
      value: ""
    validations:
      required: true
  - type: textarea
    id: php-version
    attributes:
      label: PHP version
      placeholder: ex. 7.4
      value: ""
    validations:
      required: true
  - type: checkboxes
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      options:
        - label: Firefox
        - label: Chrome
        - label: Safari
        - label: Microsoft Edge
          required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: disable-all-plugins
    attributes:
      label: Before reporting this issue, have you tried disabling all of your plugins and testing them ?
      description: "" 
      options:
        - label: Yes
          required: true