name: Bug Report(draft)
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Please write the steps needed to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots, screen recording, code snippet
      description: If applicable, add screenshots, screen recording, code snippet to help explain your problem.
  - type: input
    id: wordpress-version
    attributes:
      label: WordPress version
      placeholder: ex. 6.7.1
    validations:
      required: true
  - type: input
    id: php-version
    attributes:
      label: PHP version
      placeholder: ex. 7.4
    validations:
      required: true
  - type: checkboxes
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      options:
        - label: "Firefox"
        - label: "Chrome"
        - label: "Safari"
        - label: "Microsoft Edge"
  - type: checkboxes
    id: disable-all-plugins
    attributes:
      label: Before reporting this issue, have you tried disabling all of your plugins and testing them ?
      options:
        - label: "Yes"
          required: true